### ISSUE TITLE
Unable to successfully install lll under Golang 1.5 within Travis CI

### ISSUE THREAD

**Issue by wchrisjohnson** [walle/lll#3]
I'm trying to get a PR I've put up to successfully get thru Travis for Go 1.5:
https://travis-ci.org/antonlindstrom/pgstore/jobs/151870208

It appears this package isn't installing properly. I'm not clear whether this is an issue with your package in some way, or the gometalinter package which is installing it. Could you give some direction wrt that please?

Thank you!

**Comment by wchrisjohnson** [comment]
bump - anyone?

**Comment by walle** [comment]
Sorry abot the late reply. Looks like it is the lll package from the logs.
Will take a look at it. Thanks for reporting!

**Comment by wchrisjohnson** [comment]
Thanks @walle !!

**Comment by walle** [comment]
Hi @wchrisjohnson I think I figured out the issue. The only build that fails is for go 1.5, this is because I'm vendoring the dependencies for lll, which is only available since go 1.6.
One thing you could try is to use/set the `GO15VENDOREXPERIMENT=1` environment variable for the build on go 1.5.

**Comment by wchrisjohnson** [comment]
Yep - this worked for me - thanks!

**Comment by walle** [comment]
No problem, glad it worked out for you!
